<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEXAjjSX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEXAjjSX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEXAjjSX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEXAjjSX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEXAjjSX\App_KernelDevDebugContainer([
    'container.build_hash' => 'EXAjjSX',
    'container.build_id' => 'ce0a84e0',
    'container.build_time' => 1630434967,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEXAjjSX');
